# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: tumblful_development
  username: postgres
  password: ce5x9ZbV-bXZacjWsmCYUPfvjI
  encoding: utf8
  template: template0
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: tumblful_test
  username: postgres
  password: ce5x9ZbV-bXZacjWsmCYUPfvjI
  encoding: utf8
  template: template0
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: tumblful_production
  username: gyqfhyuzzrrpdy
  password: ce5x9ZbV-bXZacjWsmCYUPfvjI
  encoding: utf8
  template: template0
  pool: 5
  timeout: 5000

cucumber:
  <<: *test
